# -*- coding: utf-8 -*-
"""Data_Science_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16w29E35p5m4hCW8e6IwwlhzXbFpc9lo_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.metrics import (
    classification_report, confusion_matrix, precision_score, recall_score,
    f1_score, roc_auc_score, roc_curve, silhouette_score,
    r2_score, mean_squared_error
)

sns.set(style="whitegrid")
os.makedirs("output", exist_ok=True)

from google.colab import files
uploaded = files.upload()  # choose capstone_employee_attrition_dataset.csv when prompted

df = pd.read_csv("capstone_employee_attrition_dataset.csv")
print("Shape:", df.shape)
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n", df.isnull().sum())

overall_attrition = df["attrition"].value_counts(normalize=True)
print("Overall attrition rate:\n", overall_attrition)

dept_attrition = df.groupby("department")["attrition"].apply(lambda x: (x == "Yes").mean()).sort_values(ascending=False)
print("\nAttrition rate by department:\n", dept_attrition)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
overall_attrition.plot(kind="bar", ax=axes[0], color=["#4C72B0", "#DD8452"])
axes[0].set_title("Overall Attrition Rate")
axes[0].set_ylabel("Proportion")

dept_attrition.plot(kind="bar", ax=axes[1], color="#55A868")
axes[1].set_title("Attrition Rate by Department")
axes[1].set_ylabel("Attrition Rate")

plt.tight_layout()
plt.savefig("output/attrition_overview.png")
plt.show()

df_corr = df.copy()
df_corr["attrition_binary"] = (df_corr["attrition"] == "Yes").astype(int)

numeric_cols = df_corr.select_dtypes(include=[np.number]).columns
corr_matrix = df_corr[numeric_cols].corr()

top_corr = corr_matrix["attrition_binary"].drop("attrition_binary").abs().sort_values(ascending=False)
print("Top 3 features correlated with attrition:\n", top_corr.head(3))

plt.figure(figsize=(14, 10))
sns.heatmap(corr_matrix, cmap="coolwarm", center=0, annot=False)
plt.title("Correlation Matrix (Numeric Features + Attrition)")
plt.tight_layout()
plt.savefig("output/correlation_matrix.png")
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
df.boxplot(column="monthly_income_usd", by="attrition", ax=axes[0])
axes[0].set_title("Monthly Income by Attrition")
axes[0].set_ylabel("Monthly Income (USD)")

overtime_attrition = df.groupby("overtime")["attrition"].apply(lambda x: (x == "Yes").mean())
overtime_attrition.plot(kind="bar", ax=axes[1], color="#C44E52")
axes[1].set_title("Attrition Rate by Overtime")
axes[1].set_ylabel("Attrition Rate")

plt.suptitle("")
plt.tight_layout()
plt.savefig("output/income_overtime_attrition.png")
plt.show()

print("Attrition rate by overtime:\n", overtime_attrition)

cat_cols = df.select_dtypes(include="object").columns.tolist()
cat_cols = [c for c in cat_cols if c not in ["attrition", "join_date"]]
print("Categorical columns:", cat_cols)

ohe_check = OneHotEncoder(drop="first")
ohe_check.fit(df[cat_cols])
print("Number of OneHotEncoder output columns (drop='first'):", ohe_check.get_feature_names_out().size)

target_col = "attrition"
drop_cols = ["employee_id", "join_date", target_col]

X = df.drop(columns=drop_cols)
y = df[target_col].map({"Yes": 1, "No": 0})

num_cols = X.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = X.select_dtypes(include="object").columns.tolist()
print("Numeric columns:", num_cols)
print("Categorical columns:", cat_cols)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("\nTrain attrition rate:", y_train.mean())
print("Test attrition rate:", y_test.mean())
# stratify=y keeps the Yes/No ratio identical in train and test.
# Without it, a random split could over- or under-represent the minority
# "Yes" class in either set, which would skew evaluation metrics.

preprocessor = ColumnTransformer(transformers=[
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(drop="first"), cat_cols)
])

X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)  # fit only on train, transform both

print("\nX_train shape after preprocessing:", X_train_transformed.shape)

feature_names = preprocessor.get_feature_names_out()

log_reg = LogisticRegression(max_iter=1000, class_weight="balanced")
log_reg.fit(X_train_transformed, y_train)

y_pred_lr = log_reg.predict(X_test_transformed)
y_proba_lr = log_reg.predict_proba(X_test_transformed)[:, 1]

print("Logistic Regression Results")
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1-score:", f1_score(y_test, y_pred_lr))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_lr))
print("\n", classification_report(y_test, y_pred_lr))

cm = confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["No", "Yes"], yticklabels=["No", "Yes"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Logistic Regression")
plt.savefig("output/confusion_matrix_lr.png")
plt.show()

# False positive: predicted "will leave" but employee actually stayed
#   -> wasted retention effort/budget on someone who wasn't at risk.
# False negative: predicted "will stay" but employee actually left
#   -> missed a real flight risk, no intervention happened, company loses the employee.

dt = DecisionTreeClassifier(class_weight="balanced", random_state=42)
dt.fit(X_train_transformed, y_train)
y_pred_dt = dt.predict(X_test_transformed)
y_proba_dt = dt.predict_proba(X_test_transformed)[:, 1]

rf = RandomForestClassifier(class_weight="balanced", random_state=42)
rf.fit(X_train_transformed, y_train)
y_pred_rf = rf.predict(X_test_transformed)
y_proba_rf = rf.predict_proba(X_test_transformed)[:, 1]

for name, y_pred, y_proba in [("Decision Tree", y_pred_dt, y_proba_dt), ("Random Forest", y_pred_rf, y_proba_rf)]:
    print(f"\n{name} Results")
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1-score:", f1_score(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_proba))

plt.figure(figsize=(8, 6))
for name, y_proba in [("Logistic Regression", y_proba_lr), ("Decision Tree", y_proba_dt), ("Random Forest", y_proba_rf)]:
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    plt.plot(fpr, tpr, label=f"{name} (AUC={roc_auc_score(y_test, y_proba):.3f})")

plt.plot([0, 1], [0, 1], "k--", label="Random baseline")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves - Model Comparison")
plt.legend()
plt.savefig("output/roc_curves.png")
plt.show()

importances = pd.Series(rf.feature_importances_, index=feature_names).sort_values(ascending=False)
print("Top 5 features driving attrition:\n", importances.head(5))

plt.figure(figsize=(10, 6))
importances.head(10).plot(kind="barh")
plt.gca().invert_yaxis()
plt.title("Top 10 Feature Importances - Random Forest")
plt.xlabel("Importance")
plt.tight_layout()
plt.savefig("output/feature_importance.png")
plt.show()

param_grid = {"C": [0.01, 0.1, 1, 10]}
grid_search = GridSearchCV(
    LogisticRegression(max_iter=1000, class_weight="balanced"),
    param_grid=param_grid, cv=5, scoring="f1"
)
grid_search.fit(X_train_transformed, y_train)

print("Best C:", grid_search.best_params_["C"])
print("Best F1 (cross-validated):", grid_search.best_score_)

X_numeric_scaled = StandardScaler().fit_transform(df[num_cols])

inertia_list = []
k_range = range(2, 11)
for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_numeric_scaled)
    inertia_list.append(km.inertia_)

plt.figure(figsize=(8, 5))
plt.plot(list(k_range), inertia_list, marker="o")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.title("Elbow Curve")
plt.savefig("output/elbow_curve.png")
plt.show()

silhouette_scores = []
for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_numeric_scaled)
    silhouette_scores.append(silhouette_score(X_numeric_scaled, labels))

plt.figure(figsize=(8, 5))
plt.plot(list(k_range), silhouette_scores, marker="o", color="orange")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score vs k")
plt.savefig("output/silhouette_scores.png")
plt.show()

best_k_silhouette = list(k_range)[np.argmax(silhouette_scores)]
print("Best k by silhouette score:", best_k_silhouette)

chosen_k = best_k_silhouette  # or override manually based on the elbow plot, e.g. chosen_k = 4

kmeans_final = KMeans(n_clusters=chosen_k, random_state=42, n_init=10)
df["cluster"] = kmeans_final.fit_predict(X_numeric_scaled)

cluster_attrition = df.groupby("cluster")["attrition"].apply(lambda x: (x == "Yes").mean()).sort_values(ascending=False)
print("Attrition rate by cluster:\n", cluster_attrition)
print("\nHighest-attrition cluster:", cluster_attrition.idxmax())

plt.figure(figsize=(8, 5))
cluster_attrition.plot(kind="bar", color="teal")
plt.title(f"Attrition Rate by Cluster (k={chosen_k})")
plt.ylabel("Attrition Rate")
plt.savefig("output/cluster_attrition.png")
plt.show()

reg_drop_cols = ["employee_id", "join_date", "attrition", "monthly_income_usd"]
X_reg = df.drop(columns=reg_drop_cols + (["cluster"] if "cluster" in df.columns else []))
y_reg = df["monthly_income_usd"]

reg_num_cols = X_reg.select_dtypes(include=[np.number]).columns.tolist()
reg_cat_cols = X_reg.select_dtypes(include="object").columns.tolist()

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

reg_preprocessor = ColumnTransformer(transformers=[
    ("num", StandardScaler(), reg_num_cols),
    ("cat", OneHotEncoder(drop="first"), reg_cat_cols)
])

X_train_reg_t = reg_preprocessor.fit_transform(X_train_reg)
X_test_reg_t = reg_preprocessor.transform(X_test_reg)
reg_feature_names = reg_preprocessor.get_feature_names_out()

lin_reg = LinearRegression()
lin_reg.fit(X_train_reg_t, y_train_reg)
y_pred_lin = lin_reg.predict(X_test_reg_t)

rf_reg = RandomForestRegressor(random_state=42)
rf_reg.fit(X_train_reg_t, y_train_reg)
y_pred_rf_reg = rf_reg.predict(X_test_reg_t)

for name, y_pred in [("Linear Regression", y_pred_lin), ("Random Forest Regressor", y_pred_rf_reg)]:
    r2 = r2_score(y_test_reg, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test_reg, y_pred))
    print(f"{name} -> R2: {r2:.4f}, RMSE: {rmse:.2f}")

coef_series = pd.Series(lin_reg.coef_, index=reg_feature_names).sort_values(key=abs, ascending=False)
print("Top 5 features by coefficient magnitude:\n", coef_series.head(5))

top_feature = coef_series.index[0]
top_coef = coef_series.iloc[0]
print(f"\n'{top_feature}' has the strongest association with income.")
print(f"Interpretation: holding other features constant, a one-unit increase in this "
      f"(standardized) feature is associated with a ${top_coef:,.2f} change in monthly income.")

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(max_iter=1000))
])
pipe.fit(X_train[num_cols], y_train)  # fits scaler and model together, reusable on new data without manual refitting

import shutil
shutil.make_archive("output_plots", "zip", "output")
files.download("output_plots.zip")

